### ISSUE TITLE
No module named ronnia.bots.twitch_bot

### ISSUE THREAD

**Issue by flapczek** [aticie/ronnia-selfhost#3]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from ronnia.bots.twitch_bot import TwitchBot
ImportError: No module named ronnia.bots.twitch_bot

**Comment by aticie** [comment]
You need to add the repository folder to the `PYTHONPATH` environment variable. 

If you are using a IDE like PyCharm, in the Run/Debug configurations, make sure these 2 boxes are checked: 
![image](https://user-images.githubusercontent.com/25616662/199257862-5ac6f68f-37f7-4118-9d2c-0c0e3b4d8328.png)

And have the working directory point to the root folder.

**Comment by flapczek** [comment]
ERROR: Failed building wheel for yarl
Failed to build multidict yarl
ERROR: Could not build wheels for multidict, yarl, which is required to install pyproject.toml-based projects

and i got this when i tried install requirements on windows

**Comment by aticie** [comment]
I would need to see more of the error output to help you, but is there a reason for you to run this yourself? 

You can use the binaries from: https://github.com/aticie/ronnia-selfhost/releases/tag/v0.0.2

Edit: My first instinct is that you are using an incompatible python version. Try using python 3.10.

**Comment by flapczek** [comment]
I got this error again
![image](https://user-images.githubusercontent.com/52840700/199378698-12eb65e8-a7f5-4830-a9bb-1d93921f4de2.png)

I tried add something like this to environment variable
![image](https://user-images.githubusercontent.com/52840700/199379029-7c0b116c-ef90-4ef2-8cbf-8932541b9bff.png)
![image](https://user-images.githubusercontent.com/52840700/199379042-d4a9e365-c3fa-4a02-ae74-bb72153286a1.png)
but still im getting this error

**Comment by aticie** [comment]
You should run it from the root folder, like this:

`python ronnia/main.py`

and also environment variable should point to the root folder (ronnia-selfhost).

**Comment by flapczek** [comment]
ok its working but i have one more question 
![image](https://user-images.githubusercontent.com/52840700/199511682-b52cb5c6-7148-42fc-b4bb-ae9146f41505.png)
username in the twitch section in the config it means the streamer or the bot account?

**Comment by aticie** [comment]
It should be your streamer account. The selfhost version runs on your own account, doesn’t have an additional bot account.
