### ISSUE TITLE
ModuleNotFoundError: No module named 'ronnia'

### ISSUE THREAD

**Issue by sqzme** [aticie/ronnia-selfhost#4]
c:\Users\user\Desktop\ronnia\ronnia>py main.py
Traceback (most recent call last):
  File "c:\Users\user\Desktop\ronnia\ronnia\main.py", line 4, in <module>
    from ronnia.bots.twitch_bot import TwitchBot
ModuleNotFoundError: No module named 'ronnia'

**Comment by aticie** [comment]
Take a look at #3 or #2
