### ISSUE TITLE
Srry to bother u but what is the pip requirement

### ISSUE THREAD

**Issue by Gragstak** [aticie/ronnia-selfhost#6]
all in the title

**Comment by aticie** [comment]
Have you tried signing up on the website: https://ronnia.me/

Using the selfhost version might not be suitable for you. You can use the bot from the website.

**Comment by Gragstak** [comment]
i already tried it and that dont work

**Comment by aticie** [comment]
It should work when you stream the game. If you want to test it, you should enable the test mode on the settings page.

**Comment by Gragstak** [comment]
ok i will try

**Comment by Gragstak** [comment]
Ok yes it work that cool rlly thx to u
